### PR TITLE
[FIX JENKINS-34538] Fix duplicated rows when displayName is changed

### PR DESCRIPTION
**Pull request by roidelapluie**
Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>

### CODE REVIEW

**Comment by roidelapluie** [comment]
Tested ; works as expected

**Comment by tfennelly** [comment]
LGTM, but @svanoort needs to review it too and sign off on it.

**Comment by svanoort** [comment]
👍  after doing more testing, this looks like it works well to me.

**Comment by roidelapluie** [comment]
:tada:

**Pull request merged**
