### PR TITLE
[JENKINS-46096] Avoid display at bottom of page

### PR DESCRIPTION
**Pull request by ssbarnea**
Fixes [JENKINS-46096](https://issues.jenkins-ci.org/browse/JENKINS-46096)

### CODE REVIEW

**Comment by ssbarnea** [comment]
@svanoort Please review this oneliner, which reverts https://github.com/jenkinsci/pipeline-stage-view-plugin/pull/35

**Comment by svanoort** [comment]
@ssbarnea Thanks for the contribution, but I think a simple revert won't do it -- the idea behind #35 was solid *if* there was enough screen real-estate -- I think it needs a more comprehensive fix so the layout reflows correctly. 

For review of the CSS change, we should also have a before-and-after screenshots to show the bug and the result of the new layout.   Thanks!

**Comment by JeanChristopheMorinRodeoFX** [comment]
Hi guys, just wondering if there was any work being done on this? Having the stage view overflowing on the warnings/tests report is a real pain... I think I'd personally prefer to have the stage view lower in the screen than having a broken UI. Yes it's not pretty to the eyes but at least all widgets/components would work compared to what we have right now.

What do you guys think?

**Comment by TobiX** [comment]
This is now hopefully obsolete, thanks to #72

**Pull request closed without merging**
