### PR TITLE
Display empty stages with another color and status

### PR DESCRIPTION
**Pull request by vvanholl**
When using declarative pipelines, skipped stages from a "when" clause are
displayed as "SUCCESS" in green. This is a bit misunderstanding because
you can think the stage was effectively ran.

With this commit, skipped stages are displayed in gray and have the
"EMPTY" status.

### CODE REVIEW

**Comment by vvanholl** [comment]
As an exemple with the following pipeline :

````
pipeline{
    agent any
    stages{
        stage("build"){
            steps{
                sh("echo build")
            }
        }
        stage("test"){
            steps{
                sh("echo test")
            }
        }
        stage("publish"){
            when{
                branch "master"
            }
            steps{
                sh("echo publish")
            }
        }
    }
}
```
![image](https://user-images.githubusercontent.com/2646864/29242371-67c4039a-7f8c-11e7-9415-f492785d540d.png)

**Comment by Sulinskii** [comment]
Hey, good job! I find it very useful for me.

**Comment by svanoort** [comment]
@vvanholl This looks like a pretty reasonable addition and AFAICT the code looks correct (though it's generally preferred to see a new status in the Pipeline Graph Analysis plugin, where Blue Ocean can consume it, if possible).  

However, it does still need testcases before I can merge it.

**Comment by mvanini** [comment]
Good idea! Waiting for the merge.
I think it would be more clear if you change "empty" with "skipped".

**Comment by svanoort** [comment]
@mvanini It's not mergeable without appropriate test coverage -- if you are waiting for merge, you can make that happen by providing a PR replacing this one which uses this branch as its base and includes tests.

**Comment by alexmc6** [comment]
I agree this is a good idea. I guess the original requester has lost interest in this PR? 
I would be interested to see if this appears in historical builds where a stage has been introduced. Currently those stages disappear - when IMHO it would be better for them to still be displayed - but with the missing stages in grey.

**Comment by anandvarkeyphilips** [comment]
Is it solved now??

**Comment by dcalap** [comment]
Any advance or workaround/plugin?

**Pull request closed without merging**
