### PR TITLE
Link to full node log from the window

### PR DESCRIPTION
**Pull request by olivergondza**
Switching from the convenient log thing to full log listing is annoying, and in case the logs are longish, often necessary. This adds direct link.

psw-link

### CODE REVIEW

**Comment by olivergondza** [comment]
The build failure appears to the the same windows problem master have.

**Comment by olivergondza** [comment]
@svanoort, can you have a look, please?

**Comment by olivergondza** [comment]
Let's see if there are opinions elsewhere - @jenkinsci/code-reviewers

**Comment by svanoort** [comment]
@olivergondza  I'm seeing that tests are still showing failures here -- please don't simply merge directly.

**Pull request merged**
