### PR TITLE
Maximize popup window size for using screen estate

### PR DESCRIPTION
**Pull request by ssbarnea**
[JENKINS-44470](https://issues.jenkins-ci.org/browse/JENKINS-44470)

### CODE REVIEW

**Comment by svanoort** [comment]
Thank you for submitting this!  It looks very appealing, but please can you include a screenshot of the result?

Will need to do some manual testing at a variety of resolutions and browsers to verify if this works correctly in all the cases, so may be a while before I can get back with a clear mergeable/changes needed result.

**Comment by ssbarnea** [comment]
I am still working on polishing this as I found some problems during testing. I will be back with updates and screenshots! Everyone loves them :)

**Comment by svanoort** [comment]
@ssbarnea Did you ever get this to where you're happy with it?  I'm doing a sweep through PRs this week to try to get everything tested/merged, and this would be a good candidate for the next release.

**Comment by ssbarnea** [comment]
@svanoort Thanks for pinging me on this as I didn't do anything on it due to other priorities. But your sale point convinced me to spend an extra hour or two and fix it.

**Comment by svanoort** [comment]
@ssbarnea Any word on this change?  Still looking to include it into a release

**Pull request closed without merging**
