### PR TITLE
Take in final pom versions and bump version for release

### PR DESCRIPTION
**Pull request by svanoort**
What is says on the tin.

Picks up https://github.com/jenkinsci/pipeline-graph-analysis-plugin/pull/5

@reviewbybees

### CODE REVIEW

**Comment by svanoort** [comment]
Comment: will fail to build until block scoped stage is released fully to the public.

**Comment by jglick** [comment]
> will fail to build until block scoped stage is released fully to the public

So this is not technically ready for review.

For things like this I think no PR is needed—you are just bumping up dependencies to public releases, and setting the next version.

**Comment by svanoort** [comment]
@jglick Stage view and block-scoped stage should be released at the same time, to ensure compatibility for all users.

**Comment by svanoort** [comment]
Merging since it's just a pom update and changes are already validated

**Pull request merged**
