### PR TITLE
Link to full node log from the window

### PR DESCRIPTION
**Pull request by olivergondza**
Resubmitting https://github.com/jenkinsci/pipeline-stage-view-plugin/pull/61

Switching from the convenient log thing to full log listing is annoying, and in case the logs are longish, often necessary. This adds direct link.

psw-link

@svanoort, I am refiling the PR  have merge prematurely. Please review.

### CODE REVIEW

**Comment by olivergondza** [comment]
Is there any update? I would really like to get this trivial thing integrated. Thanks!

**Comment by abayer** [comment]
Re-running the build.

**Comment by olivergondza** [comment]
The tests on windows are failing for ages. Should we not better be without them?

**Comment by olivergondza** [comment]
Guys is there any way to move this forward? I see maintainers are busy and my attempts to take a lead and integrate this was not appreciated in the past...

**Comment by olivergondza** [comment]
@olamy, Thanks!

**Pull request merged**
