### PR TITLE
Fix Inconsistent Parallel Stage Order

### PR DESCRIPTION
**Pull request by lsouchard**
This solution is offered to resolve the JIRA [JENKINS-63115](https://issues.jenkins-ci.org/browse/JENKINS-63115) that I also created to detail the issue. This solution borrows from the PR #63 from @Nuh which have become stale.

### CODE REVIEW

**Comment by anthonyemerson** [comment]
is it possible this would also fix https://issues.jenkins-ci.org/browse/JENKINS-62366 ? I suspect 62366 happens because the parallel stages change the run order which Jenkins registers as a new config and so the old stage history is wiped while running

**Comment by lsouchard** [comment]
Yes it should, I didn't see this JIRA and created my own but the behavior described is almost the same. For some reason with parallel stages `ForkScanner.visitSimpleChunks` doesn't visit the nodes of a run in the same order while running and once done. Unfortunately this is too deep in Jenkins API to fix it myself. That's why I dealt with it on this plugin's API directly after visiting and collecting the stage nodes. To be clear the behavior seen in the screenshots of both JIRAs is resulting from displaying lines of runs starting from the most recent one and adding older runs line by line that are only allowed to have more subsequent stages than the one above and stopping as soon as a run break that rule.

**Comment by anthonyemerson** [comment]
@svanoort Any chance we can get this prioritized to go in? Seems a simple fix for a major quality of life issue

**Comment by jquinc30** [comment]
@olamy is still active on the project, any chance to have a quick look at this pr as changes are pretty small ?

**Comment by olamy** [comment]
would be good to have some tests for this to avoid regression in the future.

**Comment by anthonyemerson** [comment]
@lsouchard you up for adding testing around this?

**Comment by lsouchard** [comment]
@anthonyemerson Yes I will. I am in the middle of something right now but I will add some probably later this week.

**Comment by anthonyemerson** [comment]
Anyone else super excited!, Thanks @lsouchard This is going to make my life sooooo much easier

**Comment by lsouchard** [comment]
Here is a unit test to check it. I would have preferred to fully test the sorting of the stage nodes in RunExt#createNew right after the ChunkVisitor is done collecting the stages and comparing them. However, the static nature of all these methods prevents me from mocking any of these. The only solution would have been to create a mock of WorkflowRun for the ChunkVisitor to collect stages from, but the way this visitor do so is to obscure for me to build the mock I need on an object so massive. About my test, I am sorry to use sleep in the script but I haven't found any way to share a lock between the script and the test (groovy's sandbox preventing from accessing any singleton). So I had to allow the script to sleep for 2 seconds, It seems plenty enough to query the API and gather the data needed to test the order of the stages while the job is running. If anyone has any advice on how to improve on those issues, I would gladly implement those changes.

**Comment by olamy** [comment]
@lsouchard thanks a lot that's a good test! I perfectly understand how it's a pain :)

**Comment by agabrys** [comment]
Hello 🙂 The fix doesn't solve the issue (I tested the latest release [2.17](https://github.com/jenkinsci/pipeline-stage-view-plugin/releases/tag/pipeline-stage-view-2.17)). I described the problem here: [JENKINS-63115](https://issues.jenkins-ci.org/browse/JENKINS-63115?focusedCommentId=399364&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-399364).

**Pull request merged**
